### ISSUE TITLE
Error while running dockm8.ipynb

### ISSUE THREAD

**Issue by abiotik** [DrugBud-Suite/DockM8#57]
if prepare_protein == True:
    prepared_receptor = prepare_protein_protoss(receptor)
else:
    prepared_receptor = receptor

#Create a temporary folder for all further calculations
w_dir = prepared_receptor.parent / prepared_receptor.stem
print('The working directory has been set to:', w_dir)
(w_dir).mkdir(exist_ok=True)

if pocket == 'Reference':
    pocket_definition = get_pocket(ref_file, prepared_receptor, 10)
    print(pocket_definition)
if pocket == 'RoG':
    pocket_definition = get_pocket_RoG(ref_file, prepared_receptor)
    print(pocket_definition)
elif pocket == 'Dogsitescorer':
    pocket_definition = binding_site_coordinates_dogsitescorer(prepared_receptor, w_dir, method='Volume')
 
This code  gave the following error.

{
	"name": "JSONDecodeError",
	"message": "Expecting value: line 1 column 1 (char 0)",
	"stack": "---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/requests/models.py:974, in Response.json(self, **kwargs)
    973 try:
--> 974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File ~/opt/anaconda3/envs/dockm8/lib/python3.10/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File ~/opt/anaconda3/envs/dockm8/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 \"\"\"Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 \"\"\"
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File ~/opt/anaconda3/envs/dockm8/lib/python3.10/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError(\"Expecting value\", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In[4], line 2
      1 if prepare_protein == True:
----> 2     prepared_receptor = prepare_protein_protoss(receptor)
      3 else:
      4     prepared_receptor = receptor

File ~/Desktop/tik/DockM8/scripts/protein_preparation.py:81, in prepare_protein_protoss(receptor)
     79     query = {'protein_file': upload_file}
     80     # Submit the job to ProtoSS and get the job submission response
---> 81     job_submission = requests.post(PROTOSS, files=query).json()
     83 # Poll the job status until it is completed
     84 protoss_job = poll_job(job_submission['job_id'], PROTOSS_JOBS)

File ~/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/requests/models.py:978, in Response.json(self, **kwargs)
    974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 978     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
}

**Comment by Tonylac77** [comment]
Hi, Please provide the cell that defines the conditions (below the "Set up"). Which data are you using (the provided test data or custom data? This error is due to the ProToss server, it could just be a case of retrying the query several times until it goes through. Some firewall rules may also prevent the query from being done properly. In the future, please use the provided issue template for bug reports and fill out the information required.

**Comment by abiotik** [comment]
> Hi, Please provide the cell that defines the conditions (below the "Set up"). Which data are you using (the provided test data or custom data? This error is due to the ProToss server, it could just be a case of retrying the query several times until it goes through. Some firewall rules may also prevent the query from being done properly. In the future, please use the provided issue template for bug reports and fill out the information required.

Thanks for the quick reply, after reloading the issue was solved.
I am following the dock8.ipynb and got the definition error

docking(w_dir, prepared_receptor, pocket_definition, software, docking_programs, exhaustiveness, n_poses, ncpus, 'concurrent_process')
concat_all_poses(w_dir, docking_programs, prepared_receptor, ncpus, bust_poses=False)



NameError                                 Traceback (most recent call last)
Cell In[13], [line 1](vscode-notebook-cell:?execution_count=13&line=1)
----> [1](vscode-notebook-cell:?execution_count=13&line=1) docking(w_dir, prepared_receptor, pocket_definition, software, docking_programs, exhaustiveness, n_poses, ncpus, 'concurrent_process')
      [2](vscode-notebook-cell:?execution_count=13&line=2) concat_all_poses(w_dir, docking_programs, prepared_receptor, ncpus, bust_poses=False)

NameError: name 'pocket_definition' is not defined

**Comment by Tonylac77** [comment]
I noticed that in the set up cell, the pocket is defined as 'reference' (with no capitals) while in the pocket extraction cell it is defined as 'Reference'. Please ensure those two match your code, I will upload a fix for that. Then make sure you run the pocket extraction cell before running the docking cell and that should take care of your current error.

**Comment by abiotik** [comment]
@Tonylac77  Thanks for the reply the error was solved, besides that I was able to run the GUI. All the test runs were successful but after I input another pdb which wasn't in your repo I got this error.
Traceback (most recent call last):
  File "/home/nikola/Desktop/tik/DockM8/dockm8.py", line 495, in <module>
    run_command(**vars(args))
  File "/home/nikola/Desktop/tik/DockM8/dockm8.py", line 440, in run_command
    dockm8(software=Path(kwargs.get('software')),
  File "/home/nikola/Desktop/tik/DockM8/dockm8.py", line 268, in dockm8
    select_poses(method, clustering_method, w_dir, prepared_receptor,
  File "/home/nikola/Desktop/tik/DockM8/scripts/clustering_functions.py", line 191, in select_poses
    all_poses['Pose_Number'] = all_poses['Pose ID'].str.split('_').str[2].astype(int)
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply(
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/nikola/opt/anaconda3/envs/dockm8/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: invalid literal for int() with base 10: 'molnum'

**Comment by Tonylac77** [comment]
Ok, sorry about the reoccuring errors. Can you please provide me with the allposes.sdf file that was generated after the docking? Also which docking program did you use in this case?

**Comment by abiotik** [comment]
Sure, I used GNINA SMINA, here is the all poses file https://drive.google.com/file/d/1doJ6bfiALK8uVNNKDWwIhz2fAMgwfl9B/view?usp=sharing

**Comment by Tonylac77** [comment]
The issue comes from the fact that the ID of the compound was not generated properly. Please ensure that your input file for the library (i.e. your input .sdf file) has a column that can be used as an identifier. You can use free software such as DataWarrior to ensure the compounds have a name when you save the file.
