### ISSUE TITLE
Questions regarding binding box

### ISSUE THREAD

**Issue by abiotik** [DrugBud-Suite/DockM8#59]
I was wondering weather there is a way to manually define binding box size or select hotspots for virtual screening

**Comment by Tonylac77** [comment]
This can be set in the GUI in custom pocket mode : 
![image](https://github.com/user-attachments/assets/f2e6e2e9-9f79-45e0-b4fa-ec570de2bece)

Or using the command line using the following argument (the values between the commas refer to the x y z center coordinates and x y z size respectively): 
--pocket center:12.3,45.6,78.9*size:20,20,20. 

All of this information is available in the provided documentation.
